// GET  /api/trips/[tripId]/groups  — list groups with members
// POST /api/trips/[tripId]/groups  — create a group

import { NextResponse, type NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'

// Never cache — a player needs to see a fresh group assignment when they
// return to this tab or refocus the app, not a stale response from Next's
// route-handler cache.
export const dynamic = 'force-dynamic'
export const revalidate = 0

interface Props { params: Promise<{ tripId: string }> }

export async function GET(_req: NextRequest, { params }: Props) {
  const { tripId } = await params
  const supabase   = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db: any = supabase
  const result = await db
    .from('trip_groups')
    .select('*')
    .eq('trip_id', tripId)
    .order('sort_order', { ascending: true })
    .order('created_at', { ascending: true })

  if (result.error) return NextResponse.json({ error: result.error.message }, { status: 500 })
  return NextResponse.json(result.data)
}

export async function POST(req: NextRequest, { params }: Props) {
  const { tripId } = await params
  const supabase   = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })

  const body = await req.json().catch(() => ({}))
  const requestedName = (body.name ?? '').toString().trim()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const admin: any = createAdminClient()

  // Verify organiser
  const tripRes = await admin.from('trips').select('organiser_id').eq('id', tripId).single()
  if (!tripRes.data || tripRes.data.organiser_id !== user.id) {
    return NextResponse.json({ error: 'Not authorised' }, { status: 403 })
  }

  // Get current max sort_order
  const countRes = await admin.from('trip_groups').select('sort_order').eq('trip_id', tripId).order('sort_order', { ascending: false }).limit(1)
  const sortOrder = (countRes.data?.[0]?.sort_order ?? -1) + 1

  // 31 Aug field-test bundle — group-naming bug, same root cause and
  // same fix shape as the earlier round-numbering corruption fix
  // (getRoundDisplayName). TripGroupsTab.tsx's "+ Create Playing
  // Group" button computes its default name client-side from the
  // CURRENT LOCAL groups array length at the moment of the click — if
  // the button fires twice before the first request's response
  // updates that local state (a double-tap, or a slow network), both
  // requests compute the identical "Playing Group N" name, since
  // neither has seen the other's not-yet-returned result. sortOrder
  // above is race-free (a fresh DB query at request time, not a
  // client-held count), so it's used as the authoritative source for
  // the DEFAULT name too — not just position. A genuinely custom name
  // (the client sends something other than the auto-generated
  // "Playing Group N" pattern, or a future create-with-custom-name UI)
  // is still respected: only the exact auto-generated pattern gets
  // overridden, never an organiser's own deliberate choice — renaming
  // after creation already goes through the separate PATCH route
  // unaffected by this.
  const isAutoGeneratedDefaultName = /^Playing Group \d+$/.test(requestedName) || requestedName === ''
  const name = isAutoGeneratedDefaultName ? `Playing Group ${sortOrder + 1}` : requestedName

  const insertRes = await admin.from('trip_groups').insert({
    trip_id: tripId, name, sort_order: sortOrder,
  }).select().single()

  if (insertRes.error) return NextResponse.json({ error: insertRes.error.message }, { status: 500 })
  return NextResponse.json(insertRes.data, { status: 201 })
}
