import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { buildRunAgainPrefill } from '@/lib/trips/runAgain'

interface RouteProps { params: Promise<{ tripId: string }> }

/**
 * GET /api/trips/[tripId]/run-again
 *
 * Event Management Phase 2 (10 Sep), Parts 1-2 -- builds the wizard
 * prefill payload for "Run Again" and returns it as a ready-to-use
 * URL. Does NOT create anything -- no trip is created by this route at
 * all. The actual creation happens when the organiser reviews/edits
 * this prefilled data in the existing Create Event wizard and submits
 * it there, through the existing, unchanged POST /api/trips route --
 * reusing the existing creation architecture rather than building a
 * second one, per the explicit instruction.
 *
 * SAFETY BY CONSTRUCTION, not by a checklist applied after the fact:
 * this route only ever SELECTs from trips/rounds/side_comps -- the
 * same three tables POST /api/trips itself writes to when creating a
 * trip -- and maps their columns 1:1 onto WizardTripDetails/WizardRound/
 * WizardSideCompPrefill's own fields. It has no code path that could
 * read scorecards, score_entries, side_comp_entries,
 * side_comp_lead_changes, official_winner_entry_id, moments, messages,
 * highlights, badges, or trip_members beyond the auth check below --
 * those tables are never queried here, so copying them is not a risk
 * that was mitigated, it is a risk that structurally cannot occur.
 *
 * FIELD CLASSIFICATION (Part 1's required audit, reproduced here where
 * it is actually applied):
 *   SAFE REUSABLE CONFIGURATION (copied):
 *     trips: event_type, location, description, expected_players,
 *            players_per_group, organiser_is_playing
 *     rounds: name, course_name, tee_time, holes, scoring_format,
 *             starting_hole_number, tee_set_source_id, tee_name,
 *             course_rating, slope_rating, library_holes_snapshot
 *     side_comps: comp_type, hole_number (via toWizardSideCompPrefill,
 *             the same enabled/known-type filter Edit Trip already uses)
 *   REQUIRES RESET / NEW VALUE (deliberately NOT copied, left for the
 *   organiser to set in the wizard):
 *     trips: name (starting point only, suffixed " -- Copy"),
 *            start_date, end_date (left empty -- see below)
 *     rounds: play_date (left empty), id (a fresh client id is
 *             generated by the wizard itself on each add-round action;
 *             this route never sends the source round's own id)
 *   HISTORICAL DATA -- NEVER COPIED (not queried by this route at all):
 *     trip_members (beyond the auth check), scorecards, score_entries,
 *     marker entries, side_comp_entries, side_comp_lead_changes,
 *     official_winner_entry_id, moments, messages/chat, highlights,
 *     badges, points, invite_code (the wizard generates its own on
 *     create), round/trip status, any timestamp
 *
 * is_practice is not read or carried forward at all -- Run Again only
 * ever applies to a Completed Event in the normal My Events lifecycle,
 * and the created draft is always a normal Event (POST /api/trips
 * defaults is_practice to false when the field is absent).
 */
export async function GET(_req: Request, { params }: RouteProps) {
  const { tripId } = await params
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) return NextResponse.json({ error: 'Not authenticated.' }, { status: 401 })

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const admin: any = createAdminClient()

  const tripRes = await admin.from('trips')
    .select('id, name, event_type, location, description, expected_players, players_per_group, organiser_is_playing, status, organiser_id')
    .eq('id', tripId).maybeSingle()

  if (!tripRes.data) return NextResponse.json({ error: 'Event not found.' }, { status: 404 })

  // Run Again security (Part 1) -- only the organiser who owns this
  // Event may clone its configuration. Enforced here, server-side, not
  // only by which UI buttons are shown -- the same discipline Phase 1
  // applied to the DELETE route.
  if (tripRes.data.organiser_id !== user.id) {
    return NextResponse.json({ error: 'Only the organiser can run this event again.' }, { status: 403 })
  }
  // Run Again is only offered from Completed in the product's own
  // lifecycle -- enforced server-side too, so a direct call against a
  // Live/Upcoming event (which should never even show this action)
  // cannot be used to route around that.
  if (tripRes.data.status !== 'completed') {
    return NextResponse.json({ error: 'Run Again is only available for a completed event.' }, { status: 409 })
  }

  const roundsRes = await admin.from('rounds')
    .select('id, name, course_name, tee_time, holes, scoring_format, starting_hole_number, tee_set_source_id, tee_name, course_rating, slope_rating, library_holes_snapshot')
    .eq('trip_id', tripId)
    .order('play_date', { ascending: true })

  const rounds = roundsRes.data ?? []
  const roundIds = rounds.map((r: { id: string }) => r.id)

  const sideCompsRes = roundIds.length > 0
    ? await admin.from('side_comps').select('id, round_id, comp_type, hole_number, enabled').in('round_id', roundIds)
    : { data: [] }

  const prefill = buildRunAgainPrefill(tripRes.data, rounds, sideCompsRes.data ?? [])
  const prefillUrl = `/trips/new?prefill=${encodeURIComponent(JSON.stringify(prefill))}`
  return NextResponse.json({ prefillUrl })
}
